before:
  hooks:
    - go mod download

builds:
  - binary: jsping
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386

archives:
  - id: tgz
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else if eq .Arch \"386\" }}i386{{ else }}{{ .Arch }}{{ end }}"

signs:
  - artifacts: checksum
